liveapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'liveapp'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('input_content', views.input_content, name='input_content'),
    path('save_content', views.save_content, name='save_content')
]

livepro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('liveapp.urls')),
    path('admin/', admin.site.urls),
]

liveapp/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Product(models.Model):
    image_path = models.CharField(max_length=255, default = "", blank = True)
    product_name = models.CharField(max_length=255, default = "", blank = True)
    product_price = models.CharField(max_length=30, default = "", blank = True)
    product_desc = models.TextField(max_length=2000, default = None, blank = True)

    def __str__(self):
        return self.product_name

liveapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Product
from django.urls import reverse
# Create your views here.

def index(request):
    product = Product.objects.all()
    return render(request, 'liveapp/index.html', {'product': product})    

def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'liveapp/detail.html', {'product': product})

def input_content(request):
    return render(request, 'liveapp/input_content.html', {})

def save_content(request):
    image_path = request.POST['image_path']
    product_name = request.POST['product_name']
    product_price = request.POST['product_price']
    product_desc = request.POST['product_desc']

    pr = Product(image_path=image_path, product_name=product_name, product_price=product_price, product_desc = product_desc)
    pr.save()
    product = Product.objects.all()
    
    return render(request,'liveapp/index.html', {'product': product}) 

liveapp/templates/liveapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="icon" href="https://cdn.techinasia.com/data/images/3alC4cHrPwxaZLcHXaVdtIrdZg1AipfkSizMSAzL.jpeg" type="image/x-icon"/>
        
        <title>{% block title %}{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style.css' %}" />
    </head>
<body>
    {% block header %}
        {% include 'liveapp/header.html' %}
    {% endblock  %}
    
    {% block content %}
    {% endblock  %}

    {% block footer %}
    {% endblock  %}

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

liveapp/templates/liveapp/detail.html
{% extends 'liveapp/base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
    {% load static %}
    <section>
        <div class = "container detail">
            <div class = "row detail-row">
                <div class = "col-md-4"></div>
                <div class = "col-md-4 content-row-first">
                    <img src ="{{product.image_path}}" width="380px" height="252,933"></br>
                    <h5><strong>{{product.product_name}}</strong></h5></br>
                    <h5>{{product.product_price}}</h5></br>
                    <h5>Deskripsi Produk:</h5></br>
                    <h5>{{product.product_desc}}</h5></br>
                </div>
                <div class = "col-md-4"></div>
            </div>
        </div>
    </section>
{% endblock %}

liveapp/templates/liveapp/header.html
<header class="border-bottom fixed-top">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-2 blog align-items-center">
                <span>Toko Online</span>
            </div>
            <div class="col-md-10 d-flex justify-content-start">
                <nav class="navbar">
                    <a href="{% url 'liveapp:index' %}" class="nav-link font-weight-bold">Home</a>
                </nav>
            </div>
        </div>
    </div>
</header>

liveapp/templates/liveapp/index.html
{% extends 'liveapp/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    
    <section>
        <div class="container content align-items-center">
            <div class="row content-row">
                {% for p in product %}
                <div class="col-md-4 content-row-first">
                    <img src="{{p.image_path}}" width="360px" height="252,933">
                    <h5><strong>{{p.product_name}}</strong></h5>
                    <h5>{{p.product_price}}</br></h5>
                    <h5><a href="{% url 'liveapp:detail' p.id %}">Lihat Details</a></h5>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="container form">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4 submit">
                    <p class= "new_product">
                        <a href="{% url 'liveapp:input_content' %}">Submit New product</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock  %}

liveapp/templates/liveapp/input_content.html
{% extends 'liveapp/base.html' %}

{% block title %}New Product{% endblock %}

{% block content %}
{% load static %}
    <div class="container-fluid content input justify-content-center">
        <div class = "row">
            <div class = "col-md-12 justify-content-center">
            <form action="{% url 'liveapp:save_content' %}" method="POST">
                {% csrf_token %}
                <div>
                    <p>
                        <label for="img_path">Input Image URL:</label>
                        <br>
                        <input type="text" id="img_path" name="image_path" placeholder="img/image_address" required />
                    </p>
                    <p>
                        <label for="product_name">Input Product Name:</label>
                        <br>
                        <input type="text" id="product_name" name="product_name" placeholder="Name Product" required/>
                    </p>
                    <p>
                        <label for="product_price">Input Product Price:</label>
                        <br>
                        <input type="text" id="product_price" name="product_price" placeholder=" Product Price " required/>
                    </p>
                    <p>
                        <label for="product_desc">Description:</label>
                        <br>
                        <textarea id="product_desc" name="product_desc" cols="50" rows="10" required></textarea>          
                    </p>
                    <p>
                        <input type="submit" name="submit" value="Submit" />
                    </p>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}